;uart config file

[com1]
port = /dev/ttyUSB0
baudrate = 115200
;select:5\6\7\8
bytesize = 8
;select:N\E\O\M\S
parity = N
;select:1\1.5\2
stopbits = 1
;select:None\0\1.0\...
timeout = 1


[com2]
port = /dev/ttyS1
baudrate = 115200
bytesize = 8
parity = odd
stopbits = 1
timeout = 1


